### PR TITLE
Use Github-like theme for documentation (created by PICONOMIX)

### PR DESCRIPTION
**Pull request by mimon**
Screenshot 2019-12-28 at 14 31 35

I want to suggest a theme to the documentation that resembles the style of Github. It's a style familiar to many developers and I thought that would be appropriate.

The theme source originates from https://github.com/piconomix which is under a MIT license.

The style can of course be improved further over time, but I think this is a good start.

### CODE REVIEW

**Comment by mimon** [comment]
Update since the PR was created: changed the blue color to ogre-green.

**Comment by mimon** [comment]
Any comments / feedback from Ogre devs with repo write access, regarding this PR?

**Comment by mimon** [comment]
@darksylinc what is your opinion regarding this PR? Is it something of interest?

**Comment by darksylinc** [comment]
With the picture you posted I'm having trouble noticing "What's difference", and without a live preview/sample I can't compare either.

Since it's something I need to download and take my time to view and review it; and it's not high on my priority list.

More pictures could help, or a live preview of our docs with the new theme

**Comment by mimon** [comment]
Ok, I'll see what I can come up with! Thanks

**Comment by mimon** [comment]
@darksylinc  There's now a live preview at https://mimon.github.io/ogre-next/html/index.html

The theme is more familiar to a developer hanging around Github, gitlab, bitbucket etc. The code blocks style follows in the same way...

Looking at it now, I feel it may need some more polishing (especially the API docs) to get the margins & padding correct.

**Comment by mimon** [comment]
I'm gonna close this and open a new PR with a smaller diff and interference.

**Pull request closed without merging**
