### PR TITLE
fix doxygen warnings about explicit link requests

### PR DESCRIPTION
**Pull request by jwwalker**
I went through the doxygen warnings and fixed cases where it said "warning: explicit link request to 'something' could not be resolved".  Also fixed other formatting problems in docs of `HighLevelGpuProgram::setEnableIncludeHeader`.

### CODE REVIEW

**Comment by darksylinc** [comment]
The code is not compiling in either [Linux](https://github.com/OGRECave/ogre-next/runs/6444241970?check_suite_focus=true) nor [Windows](https://ci.appveyor.com/project/MatiasNGoldberg/ogre-next/builds/43551364)

**Comment by jwwalker** [comment]
Sorry about that.  I see the problem now, but it's not immediately obvious how to solve it in a way that will produce the desired documentation formatting.  I'll have to do some more research.

**Comment by jwwalker** [comment]
I believe I have it sorted out now.

**Comment by jwwalker** [comment]
@darksylinc Hi, just wanted to make sure you noticed that this PR has been updated.

**Pull request merged**
