### PR TITLE
Manual docs edits - HLMS block reference guides

### PR DESCRIPTION
**Pull request by oldmanauz**
Start of a PR to add reference documentation for all of the HLMS blocks. Not sure I understand how the manual links work so this commit is just to make sure I'm on the right track.

### CODE REVIEW

**Comment by oldmanauz** [comment]
That makes sense. I was reading the Ogre 13 manual to help my understanding and from what I saw, it used "lod" in reference to mesh lods. This didn't make sense to me becuase a sampler block was about defining texture parameters.

**Comment by oldmanauz** [comment]
Added reference guides for Terra and Unlit datablocks.
Some more clarifications:
1. In the unlit datablock, is `diffuse_map0` treated differently to `diffuse_map1` > `diffuse_map15`?
2. In the unlit datablock, just wanted to confirm that the unlit datablocks will use "blendblock" and "macroblock"?
3. Just to confirm that the following is an inconsistancy, not a bug:
The code here in `OgreHlmsUnlitDatablock.cpp > Line 62` is used when reading a V1 material file or "HlmsParamVec"? In this code the 0 index is "diffuse_map"
```
const String c_diffuseMap[NUM_UNLIT_TEXTURE_TYPES] =
{
    "diffuse_map", <-- NO "0" ON THE END
    "diffuse_map1",
    ...
    "diffuse_map15"
};
```
`OgreHlmsJsonUnlit.cpp > line 177`: Reads "diffuse_map0" to "diffuse_map15" from the material file. (0 index is "diffuse_map0")
4. In the Terra terrain sample material file, it reads a `normalize` and `autogenerate` parameters from the datablock. These aren't read in the HlmsJsonTerra::loadMaterial function. Are they future or depreciated features?

**Comment by darksylinc** [comment]
In api/html/hlmspbsdatablockref.html it appears malformed Markdown causes everything to become bold:

> mode: Type string. Blend mode to use for each detail map. This parameter only affects the diffuse detail map. DEFAULT=NormalNonPremul.** Valid values:
NormalNonPremul: Regular alpha blending.

image

**Comment by darksylinc** [comment]
>     1. Datablock: "Transparency" block > "mode" parameter. In the documentation it references a possible "Refractive" value but in the source code it doesn't seem to allow that to be used. Is "Refractive" a valid mode parameter?

That's a bug. We support refractions (although requires special Compositor setup).Samples/2.0/ApiUsage/Refractions shows it in action

>     2. In the Terra terrain sample material file, it has a `normalize` and `autogenerate` parameters in the datablock. These aren't read in the HlmsJsonTerra::loadMaterial function. Are they future or depreciated features?

I have a lot of code I worked for a client for auto-generating beautiful materials; but I haven't been approved to release it yet (hasn't been in a while... there was a plan but...).
I wanted to reimplement it from scratch but I didn't have time for that either. So it's basically "TODO"

**Comment by oldmanauz** [comment]
@darksylinc I just rebuilt the documents from my PR and I don't have the issues you describe above:

1. HlmsPBSDatablockRef: The bold tag is closed:
```
- Block definition:
    - `mode`: Type string. Blend mode to use for each detail map. This parameter only affects the diffuse detail map. **DEFAULT=`NormalNonPremul`.** Valid values:
        - `NormalNonPremul`: Regular alpha blending. 
 ```
Picture as built on my machine:
image

2. I don't have header issue either:

> Likewise # Example Samplerblock Definition: {#sbExample} + # Example Macroblock Definition: and co. somehow aren't interpreted as a header/title:

Picture as built on my machine:
image


3. Possible causes:
 - Doxygen version missmatch? I'm on 1.9.2
 - Your first screen shot has different formating to mine. Is this a browser/OS difference?

**Comment by oldmanauz** [comment]
@eugenegff, @jwwalker, sorry to annoy you both. Could someone test this commit and see if your getting the formatting issues that darksylinc was getting above? Just trying to track down where the problem is.
Thanks.

**Comment by jwwalker** [comment]
@oldmanauz I'm not sure why you named me, I'm kind of a newbie to Ogre, but I gave it a try... I pulled your changes and ran doxygen, but I can't find the page you're looking at, or even any "Reference Guide" section.

**Comment by oldmanauz** [comment]
@jwwalker I saw that you had been one of the recent active people contributing a PR. In the documentation > Manual > HLMS: High level material system > Blocks menu > The related menu items are circled in red below:
- HLMS PBS datablock reference > Heading: Parameter: detail_diffuse[X] >Is the bold tag for the text `DEFAULT=NormalNonPremul.` closing properly?
- HLMS Macroblock reference > Heading: Example Macroblock Definition: > Is this markdown for the heading being interpreted properly?
Thanks for looking.
image

**Comment by jwwalker** [comment]
@oldmanauz This is what I see instead of those links:
Screen Shot 2021-11-16 at 8 48 22 AM

**Comment by jwwalker** [comment]
@oldmanauz Here are some of the doxygen warnings I'm getting:

```
Docs/src/manual/hlms.md:193: warning: unable to resolve reference to 'hlmsblendblockref' for \ref command
Docs/src/manual/hlms.md:194: warning: unable to resolve reference to 'hlmspbsdatablockref' for \ref command
Docs/src/manual/hlms.md:195: warning: unable to resolve reference to 'hlmsunlitdatablockref' for \ref command
Docs/src/manual/hlms.md:196: warning: unable to resolve reference to 'hlmsterradatablockref' for \ref command
Docs/src/manual/hlms.md:197: warning: unable to resolve reference to 'hlmsmacroblockref' for \ref command
Docs/src/manual/hlms.md:198: warning: unable to resolve reference to 'hlmssamplerref' for \ref command
Docs/src/manual/hlms.md:338: warning: Found unknown command '@end'
Docs/src/manual/hlms.md:644: warning: Found unknown command '@counter'
Docs/src/manual/hlms.md:644: warning: Found unknown command '@value'
Docs/src/manual/hlms.md:724: warning: Found unknown command '@insertpiece'
Docs/src/manual/hlms.md:770: warning: Found unknown command '@set'
```

**Comment by jwwalker** [comment]
@oldmanauz Yes, the 2 things you ask about look OK for me.  (I couldn't find them before because my html.cfg was out of date.)

**Comment by oldmanauz** [comment]
@jwwalker thanks a lot for taking a look. I appreciate it.

**Comment by oldmanauz** [comment]
@darksylinc are you interested in this PR still or want me to remove it?

**Comment by darksylinc** [comment]
I noticed today this PR hadn't been merged yet. I'll be taking a look tomorrow.

I think I'm gonna merge it and then fix whatever inaccuracy or problem it has as we go.

**Comment by oldmanauz** [comment]
@darksylinc Thanks. I'll look for problems after the merge. Can you please merge #246 as well, but please merge this one first as it will conflict otherwise.

**Pull request merged**
