### PR TITLE
Fix doxygen publish

### PR DESCRIPTION
**Pull request by mimon**
This should do it 😄  🤞

### CODE REVIEW

**Comment by mimon** [comment]
Hm, I see there's a 404 now on GH pages. Not what I expected I suppose 😬 . It's weirded I had not these issues in my own test repo.

**Comment by mimon** [comment]
Looks like it's not serving from the `html/` directory. So one needs to go to https://ogrecave.github.io/ogre-next/html/ to see the page

**Comment by mimon** [comment]
Perhaps [this line](https://github.com/OGRECave/ogre-next/blob/master/CMake/Templates/html.cfg.in#L898) should be changed to `./` instead

**Comment by darksylinc** [comment]
I force-push reverted that change since we can't have broken links on documentation; at least until we find the proper solution

**Comment by mimon** [comment]
> I force-push reverted that change since we can't have broken links on documentation; at least until we find the proper solution

OK. I'll have a look tomorrow, but I'm pretty sure this is the fix:
https://github.com/OGRECave/ogre-next/pull/89#issuecomment-619414327

**Pull request merged**
