### PR TITLE
Docs: point out render order if DisableSort is used

### PR DESCRIPTION
**Pull request by mimon**
Based on what @darksylinc  wrote in https://forums.ogre3d.org/viewtopic.php?f=2&t=94628#p543341

### CODE REVIEW

**Comment by darksylinc** [comment]
I find that description to be very easy to misunderstand, as it could be interpreted that DisableSort uses the order in which Items (or Entities) were created, which is not true (but it will often coincide but not always, adding confusion).

DisableSort honours the order in which addRenderableV2 (or addRenderableV1) was called. That's it.

If you're manually manipulating the RenderQueue then yes, this is useful information.

But if you're relying on the standard Ogre rendering paths (i.e. drawing regular Items) then some of these objects are added from a multithreaded context.

Order in which Items were created will often coincide because each thread is currently splitting all MovableObjects into chunks, and the threads later get collected in order.

But if you start destroying Items and then add more; released slots are recycled for new objects and that's when the order breaks. But this is an implementation side effect that is not enforced.

The only order with DisableSort that can be safely guaranteed is the order in which addRenderableV1/addRenderableV2 calls are made.

**Comment by mimon** [comment]
> I find that description to be very easy to misunderstand, as it could be interpreted that DisableSort uses the order in which Items (or Entities) were created

I understand your concern. However, since this piece of docs is specifically for `RenderQueue::addRenderableV2()` and exactly describes the behaviour of the `RenderQueue` when `DisableSort` is set, why would I confuse it with the behaviour of e.g. `SceneManager::createItem()`? I can't see the potential for misunderstanding 🤔

**Comment by darksylinc** [comment]
Just slightly reword the paragraph to say '..then the order in which renderables are added via RenderQueue::addRenderableV2 (and V1) determines...'

**Comment by mimon** [comment]
> Just slightly reword the paragraph to say '..then the order in which renderables are added via RenderQueue::addRenderableV2 (and V1) determines...'

👍 I've updated and pushed the new changes. @darksylinc

**Pull request merged**
