### PR TITLE
Code readability and performance 'insert' -> 'emplace' C++11

### PR DESCRIPTION
**Pull request by GermanAizek**
@darksylinc, I think you'll like this change.
I'm not touching on C++17, although there is a lot code to rewrite according to new standard.

### CODE REVIEW

**Comment by darksylinc** [comment]
I just fixed the clang format error, but it looks there is a compile error on Windows: https://ci.appveyor.com/project/MatiasNGoldberg/ogre-next/builds/44884164#L1195

**Comment by GermanAizek** [comment]
> I just fixed the clang format error, but it looks there is a compile error on Windows: https://ci.appveyor.com/project/MatiasNGoldberg/ogre-next/builds/44884164#L1195

@darksylinc unexpected happened, I accidentally deleted your changes, sorry.

**Comment by darksylinc** [comment]
[It failed again](https://github.com/OGRECave/ogre-next/actions/runs/3128822812/jobs/5077290011#step:3:926), this time a silly error

Btw if you're on Linux and you have clang-format-13 installed, you can fix Clang Format errors with:

```bash
cd .github/workflows
python3 run_clang_format.py --fix_broken_files
```

**Comment by GermanAizek** [comment]
> [It failed again](https://github.com/OGRECave/ogre-next/actions/runs/3128822812/jobs/5077290011#step:3:926), this time a silly error
> 
> Btw if you're on Linux and you have clang-format-13 installed, you can fix Clang Format errors with:
> 
> ```shell
> cd .github/workflows
> python3 run_clang_format.py --fix_broken_files
> ```

oh thx for tip

**Comment by darksylinc** [comment]
I just pushed a fix for clang format.

CI checks are running.

**Comment by GermanAizek** [comment]
> [It failed again](https://github.com/OGRECave/ogre-next/actions/runs/3128822812/jobs/5077290011#step:3:926), this time a silly error
> 
> Btw if you're on Linux and you have clang-format-13 installed, you can fix Clang Format errors with:
> 
> ```shell
> cd .github/workflows
> python3 run_clang_format.py --fix_broken_files
> ```

@darksylinc on Windows, this command did not work for me on Python 3.10
Argument "fix_broken_files" not found

**Comment by darksylinc** [comment]
> on Windows, this command did not work for me on Python 3.10
> Argument "fix_broken_files" not found

Yeah, I never tested it on Windows.

I am currently taking care of the clang format errors due to this (plus, I haven't updated yet the PR instructions, so I can't blame contributors for not knowing).

**Comment by GermanAizek** [comment]
@darksylinc, You can merge PR, they do not particularly critically affect a lot code and functionality

**Comment by darksylinc** [comment]
I approve this PR.
Eugene approves this PR. 

All units test are passing on Windows (D3D11) and Linux (GL, Vulkan).

**Comment by darksylinc** [comment]
Thank you for your PR!

**Pull request merged**
