### PR TITLE
Backport USE_NEW_PROJECT_NAME to 2.3

### PR DESCRIPTION
**Pull request by mjcarroll**
When enabled, all projects and libraries will be named "OgreNext"
instead of Ogre.

This will help minimize patching when using OGRE 2.3 in a colcon workspace with `Gazebo` as well dropping the patch from packaging jobs.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Don't merge this yet, one of the samples was broken when the flag is enabled.

**Comment by darksylinc** [comment]
This likely happens as well with the tests (set OGRE_BUILD_TESTS on)

**Comment by mjcarroll** [comment]
> This likely happens as well with the tests (set OGRE_BUILD_TESTS on)

I will double check tests, then.

**Comment by mjcarroll** [comment]
Build is clean for me with 
```
      "-DOGRE_USE_NEW_PROJECT_NAME:BOOL=ON",
      "-DOGRE_BUILD_TESTS:BOOL=ON"
```

**Comment by darksylinc** [comment]
I think it's ok if not *everything* Ogre 2.3 supports the OgreNext name change, because this feature will actually be officially introduced in 3.0 (on by default in 4.0; deprecated by 5.0, removed by 6.0)

This PR merely aims at making gazebo integration/maintenance easier

**Pull request merged**
