### PR TITLE
Docs of HlmsListener::getPassBufferSize, HlmsListener:: preparePassBuffer

### PR DESCRIPTION
**Pull request by jwwalker**
While learning to use `HlmsListener::getPassBufferSize` and `HlmsListener::preparePassBuffer`, I thought that their documentation could be clearer, so I revised it.

### CODE REVIEW

**Review by darksylinc — CHANGES_REQUESTED** [review]
The `@result` should be turned into `@return` for consistency.
Likely for better formatting the whole comment should be trurned into /* */ style

**Comment by jwwalker** [comment]
@darksylinc OK, how's this?

**Comment by darksylinc** [comment]
Hi!

Clang Format CI is failing. I can't fix it for you because I don't have Write access to your repo.

You can apply this patch to fix it:

```diff
diff --git a/OgreMain/include/OgreHlmsListener.h b/OgreMain/include/OgreHlmsListener.h
index 8c58b8fdd2..ded80024c5 100644
--- a/OgreMain/include/OgreHlmsListener.h
+++ b/OgreMain/include/OgreHlmsListener.h
@@ -152,7 +152,7 @@ namespace Ogre
 
         /** Listeners should return the number of extra bytes they wish to allocate for storing
             additional data in the pass buffer.
-        
+
             The actual data will be provided by a preparePassBuffer() override.
         @return
             Number of bytes of additional pass buffer data to allocate.  Must be a multiple of 16.
```

Btw if you have python3 and clang-format-13 installed you can run (I only run this in Linux, but I think it should be able to run on macOS):

```bash
cd .github/workflows
python3 run_clang_format.py --fix_broken_files
```

And it will automatically apply clang format for you.

**Comment by jwwalker** [comment]
@darksylinc Sorry, it should be OK now.

**Pull request merged**
